spring:
  application:
    name: agentdemo
  ai:
    openai:
      api-key: sk-fzgzofbfycwithholklhmvyzjabnsqsaurinjottpmidjrjz
      base-url: https://api.siliconflow.cn
      chat:
        options:
          model: Qwen/Qwen3-32B
    vectorstore:
      milvus:
        client:
          host: localhost
          port: 19530
        collection-name: knowledge
        embedding-dimension: 1536

rag:
  file-storage:
    location: D:/rag-files/upload

